### ISSUE TITLE
THTensorCopy copy error

### ISSUE THREAD

**Issue by TheAnneO** [pathak22/context-encoder#1]
I am attempting to run your code, but I am encountering an error when running train.lua.

The only changes I made to the code were commenting out some of the trainHook function in donkey_folder.lua since I did not want my images to be randomly cropped and changing the number of channels to be 1 since all of the images in my data are 128 x 128 grayscale images.

I am running the code on Ubuntu 16.04 on CPU only. This is the latest version of torch. I have installed all required dependencies by running luarocks install torch, luarocks install nn, luarocks install optim, luarocks install threads, luarocks install argcheck, luarocks install sys, luarocks install xlua, and luarocks install image.

I've been going nuts for 3 days trying to resolve this error. I'd be grateful for any help I could get.

anne@Anne:~/Desktop/context-encoder$ DATA_ROOT=dataset/train th train.lua
{
  ntrain : inf
  nc : 1
  noiseGen : 0
  beta1 : 0.5
  nThreads : 4
  display_iter : 50
  niter : 25
  batchSize : 64
  ndf : 64
  fineSize : 0
  nz : 100
  wtl2 : 0
  loadSize : 0
  gpu : 0
  ngf : 64
  conditionAdv : 0
  noisetype : "normal"
  lr : 0.0002
  manualSeed : 0
  name : "train1"
  overlapPred : 0
  nBottleneck : 100
  nef : 64
  display_id : 10
  display : 0
}
Seed: 5354  
Starting donkey with id: 2 seed: 5356
table: 0x418bb2f8
Starting donkey with id: 1 seed: 5355
table: 0x412fd340
Starting donkey with id: 4 seed: 5358
table: 0x41b19aa8
Starting donkey with id: 3 seed: 5357
table: 0x41e394e0
Loading train metadata from cache
Loading train metadata from cache
Loading train metadata from cache
Loading train metadata from cache
Dataset Size:     200000  
LR of Gen is     1    times Adv  
NetG:    nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> (16) -> (17) -> output](1): nn.Sequential {
    [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> output](1): nn.SpatialConvolution(1 -> 64, 4x4, 2,2, 1,1)
    (2): nn.LeakyReLU(0.2)
    (3): nn.SpatialConvolution(64 -> 64, 4x4, 2,2, 1,1)
    (4): nn.SpatialBatchNormalization
    (5): nn.LeakyReLU(0.2)
    (6): nn.SpatialConvolution(64 -> 128, 4x4, 2,2, 1,1)
    (7): nn.SpatialBatchNormalization
    (8): nn.LeakyReLU(0.2)
    (9): nn.SpatialConvolution(128 -> 256, 4x4, 2,2, 1,1)
    (10): nn.SpatialBatchNormalization
    (11): nn.LeakyReLU(0.2)
    (12): nn.SpatialConvolution(256 -> 512, 4x4, 2,2, 1,1)
    (13): nn.SpatialBatchNormalization
    (14): nn.LeakyReLU(0.2)
    (15): nn.SpatialConvolution(512 -> 100, 4x4)
  }
  (2): nn.SpatialBatchNormalization
  (3): nn.LeakyReLU(0.2)
  (4): nn.SpatialFullConvolution(100 -> 512, 4x4)
  (5): nn.SpatialBatchNormalization
  (6): nn.ReLU
  (7): nn.SpatialFullConvolution(512 -> 256, 4x4, 2,2, 1,1)
  (8): nn.SpatialBatchNormalization
  (9): nn.ReLU
  (10): nn.SpatialFullConvolution(256 -> 128, 4x4, 2,2, 1,1)
  (11): nn.SpatialBatchNormalization
  (12): nn.ReLU
  (13): nn.SpatialFullConvolution(128 -> 64, 4x4, 2,2, 1,1)
  (14): nn.SpatialBatchNormalization
  (15): nn.ReLU
  (16): nn.SpatialFullConvolution(64 -> 1, 4x4, 2,2, 1,1)
  (17): nn.Tanh
}
NetD:    nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> output](1): nn.SpatialConvolution(1 -> 64, 4x4, 2,2, 1,1)
  (2): nn.LeakyReLU(0.2)
  (3): nn.SpatialConvolution(64 -> 128, 4x4, 2,2, 1,1)
  (4): nn.SpatialBatchNormalization
  (5): nn.LeakyReLU(0.2)
  (6): nn.SpatialConvolution(128 -> 256, 4x4, 2,2, 1,1)
  (7): nn.SpatialBatchNormalization
  (8): nn.LeakyReLU(0.2)
  (9): nn.SpatialConvolution(256 -> 512, 4x4, 2,2, 1,1)
  (10): nn.SpatialBatchNormalization
  (11): nn.LeakyReLU(0.2)
  (12): nn.SpatialConvolution(512 -> 1, 4x4)
  (13): nn.Sigmoid
  (14): nn.View(1)
}
/home/anne/torch/install/bin/luajit: /home/anne/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /home/anne/Desktop/context-encoder/data/dataset.lua:328: inconsistent tensor size at /tmp/luarocks_torch-scm-1-667/torch7/lib/TH/generic/THTensorCopy.c:7
stack traceback:
    [C]: in function 'copy'
    /home/anne/Desktop/context-encoder/data/dataset.lua:328: in function 'tableToOutput'
    /home/anne/Desktop/context-encoder/data/dataset.lua:345: in function </home/anne/Desktop/context-encoder/data/dataset.lua:335>
    [C]: in function 'xpcall'
    /home/anne/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
    /home/anne/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/anne/torch/install/share/lua/5.1/threads/queue.lua:41>
    [C]: in function 'pcall'
    /home/anne/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
    [string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
    [C]: in function 'error'
    /home/anne/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
    /home/anne/Desktop/context-encoder/data/data.lua:81: in function 'getBatch'
    train.lua:281: in function 'opfunc'
    /home/anne/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
    train.lua:413: in main chunk
    [C]: in function 'dofile'
    ...anne/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00405d50

**Comment by pathak22** [comment]
Could you resolve this error ? Sorry, I noticed this thread today (by chance) and didn't see notification.

Few things to try: 
=> Print the size of data and datatable in dataset.lua: line 328
=> What if you set this: nc=1, loadSize=129, fineSize=128 ? Does this work ?

**Comment by pathak22** [comment]
On further thinking, I realized that I have not actually supported grayscale version in code. There are some hard-coded channel-wise things, for example: https://github.com/pathak22/context-encoder/blob/master/train.lua#L283-L285

You will have to edit train.lua etc as well for your code to work on grayscale.

**Comment by myw8** [comment]
can  you  tell me   where can I  get your   train data images

**Comment by lhaof** [comment]
@myw8 https://github.com/tylin/dpatch use this code to download images from google street view

**Comment by pathak22** [comment]
Note that currently released code works much better when trained on ImageNet images. For example: see imagenet results on project webpage. 

But if you necessarily want to use street-view dataset, you can email me and I will share. Due to license policy issue, it is not allowed to release that dataset publicly.
