### ISSUE TITLE
Where is the Channel-wise fully-connected layer 

### ISSUE THREAD

**Issue by royal-feng** [pathak22/context-encoder#10]
I want to ask you for whether the Channel-wise fully-connected layer is the nBottleneck in the code? My understanding that is the transition layer between the encoder and decoder, is it right?How to expression in the Channel-wise fully-connected layer

**Comment by pathak22** [comment]
Hi ! The architecture I used in this repository is pretty simple. At the bottleneck, there are 4000 outputs for which if normal fully connected layer is used, it would result into 16M parameters which is usually fine (for e.g. AlexNet has more than that). This is described in Figure-9(a) in paper. 

But if we were to use AlexNet until pool5 as generator then using normal FC would lead to about  100M parameters in single layer, hence channelwise-FC would be useful there. See Figure-9(b) in paper. For simple graphics inpainting task, we do not need to put AlexNet until pool5 architecture in generator. That is required for feature learning.

**Comment by NerminSalem** [comment]
hi
in figure 9a the last conv layer s' dimension is 4*4*512 in encoder part, what is its equivalent in alexNet architecture 
thanks
