### ISSUE TITLE
Train Context Encoders

### ISSUE THREAD

**Issue by NerminSalem** [pathak22/context-encoder#11]
hi 
i m trying to train the context encoder but i m getting this error after the epoch no.20, i m using cpu mode as my laptop doesn't support CUDA
Epoch: [20][       3 /        3]	 Time: 29.860  DataTime: 0.002    Err_G_L2: 0.0748   Err_G: 1.6929  Err_D: 0.4178	
/home/nermin/torch/install/bin/lua: ...me/nermin/torch/install/share/lua/5.1/torch/File.lua:210: write error: wrote 24686288 blocks instead of 32768000 at /home/nermin/torch/pkg/torch/lib/TH/THDiskFile.c:353
stack traceback:
	[C]: in function 'write'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:210: in function <...me/nermin/torch/install/share/lua/5.1/torch/File.lua:107>
	[C]: in function 'write'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:210: in function 'writeObject'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:235: in function 'writeObject'
	...ome/nermin/torch/install/share/lua/5.1/nn/Module.lua:188: in function 'write'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:210: in function 'writeObject'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:235: in function 'writeObject'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:235: in function 'writeObject'
	...ome/nermin/torch/install/share/lua/5.1/nn/Module.lua:188: in function 'write'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:210: in function 'writeObject'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:235: in function 'writeObject'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:235: in function 'writeObject'
	...ome/nermin/torch/install/share/lua/5.1/nn/Module.lua:188: in function 'write'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:210: in function 'writeObject'
	...me/nermin/torch/install/share/lua/5.1/torch/File.lua:388: in function 'save'
	/home/nermin/context-encoder/util.lua:96: in function 'save'
	train.lua:451: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: ?
can u help?
thanks

**Comment by pathak22** [comment]
Do you have enough disk-space to save the model ? Your training seems to be running fine, but its giving error when trying to save the model. see train.lua line:451.

**Comment by NerminSalem** [comment]
Ohhhhh, i got it
Thanks alot for yr help
