### ISSUE TITLE
Loss for Inpainting

### ISSUE THREAD

**Issue by lynetcha** [pathak22/context-encoder#12]
Section 3.2 of the paper (Joint Loss) says that adversarial loss only is used for inpainting experiments, but Figure 6 shows results with L2+Adv. Can you please clarify?

**Comment by lynetcha** [comment]
Nevermind, I got it. L2 only is used for the feature learning.

**Comment by pathak22** [comment]
Yes, inpainting uses Joint loss (both): https://github.com/pathak22/context-encoder/blob/master/train.lua#L204-L208

**Comment by micklexqg** [comment]
@pathak22 , wtl2 is for what? if it is set 0 (default), then the script will be used for feature learning?
I notice there is 
![image](https://user-images.githubusercontent.com/13776012/37082359-5ed8ad9c-2227-11e8-93a5-4273f691ff3f.png) and 
![image](https://user-images.githubusercontent.com/13776012/37082393-6ee53070-2227-11e8-9282-d6186dc82ba6.png)

  in the equation 
![image](https://user-images.githubusercontent.com/13776012/37082346-52e177b2-2227-11e8-8b2b-d87b883d1d2b.png)
 in section 3. which parameters are for them in the code?
