### ISSUE TITLE
Mean Pixel Value of the Features Caffemodel

### ISSUE THREAD

**Issue by playerkk** [pathak22/context-encoder#17]
Hi, I was wondering if you subtracted the input image by some mean pixel values. If so, would it be possible to let me know what they are? Thanks.

**Comment by pathak22** [comment]
For caffe-model, I used standard imagenet-constant value mean subtraction, i.e., subtract from each pixel the following: [B,G,R] = [104,117,123].

**Comment by pathak22** [comment]
Closing this issue hoping your question is answered.
