### ISSUE TITLE
Decoder part for section 5.2, feature learning?

### ISSUE THREAD

**Issue by mcahny** [pathak22/context-encoder#18]
The prototxt and learned weight for the Alexnet encoder is here, but I wonder if there is caffe /torch implementation for the decoder part, which would include the channel-wise fully connected layer.

I would greatly appreciate if you can share the implementation.

**Comment by pathak22** [comment]
You don't need to implement Channel-wise layer separately. It can be designed using 'groups' feature in convolutional layers. For e.g. in Caffe:

=> channelWiseFC = L.Convolution(pool5, kernel_size=6, num_output=9216, stride=1, pad=0, group=256)

**Comment by mcahny** [comment]
Thanks a lot. 

Can you also show an example how the upconvolution is done? I wonder how unpooling could be done in caffe. Or are they just simple deconvolutions w/o unpooling?

**Comment by mcahny** [comment]
@pathak22 Thanks a lot.

Can you also show an example how the upconvolution is done? I wonder how unpooling could be done in caffe. Or are they just simple deconvolutions w/o unpooling?

**Comment by mcahny** [comment]
@pathak22 Thanks a lot.

Can you also show an example how the upconvolution is done? I wonder how unpooling could be done in caffe. Or are they just simple deconvolutions w/o unpooling?

and if so, what are the parameters for the deconvolutions?

**Comment by pathak22** [comment]
@mcahny Sorry for late reply. This is how deconv is done:
`def deconv(bottom, kernel_size, num_output, stride=1, pad=0, group=1):
    p = dict(kernel_size=kernel_size, stride=stride, num_output=num_output, pad=pad,
             group=group)
    return L.Deconvolution(bottom, convolution_param=p)`
