### ISSUE TITLE
 About Paris StreetView Dataset

### ISSUE THREAD

**Issue by liuppboy** [pathak22/context-encoder#19]
Hi,

I have read your paper and hope to run the code, but I cannot find the Paris StreetView Dataset. Since ImageNet is too large and difficult to train, I hope to use Paris StreetView Dataset. So could you please tell me how I can find the dataset? 

Thanks so much for your attention!

**Comment by pathak22** [comment]
If you email me, I can share the dataset with you with a private link. Google policy does not allow public sharing of street-view images.
