### ISSUE TITLE
Why we need reset conv's bias value in every iterator

### ISSUE THREAD

**Issue by Teaonly** [pathak22/context-encoder#2]
```
   netD:apply(function(m) if torch.type(m):find('Convolution') then m.bias:zero() end end)
   netG:apply(function(m) if torch.type(m):find('Convolution') then m.bias:zero() end end)
```

We can see these code in fGx and fDX, I can' understand these code. 

The bias value is determined at the last iterator training phase ?

**Comment by pathak22** [comment]
@Teaonly 
This is so because we are using BatchNorm, so bias of convolution is not needed. It gets handled by BatchNorm, and reseting it makes convergence slightly faster. Hope it answers your question. Thanks !

**Comment by Teaonly** [comment]
@pathak22  

I see.
Thank you!
