### ISSUE TITLE
Paris StreetView Dataset

### ISSUE THREAD

**Issue by NerminSalem** [pathak22/context-encoder#20]
hi @pathak22 hope u r fine
can u share the link to download the Paris StreetView Dataset?
thanks for yr help and support

**Comment by pathak22** [comment]
@NerminSalem: please email me and I will share. Google policy forbids putting a public link for streetview images. Thanks!

**Comment by NerminSalem** [comment]
i already did, kindly check yr mail, my mail is nfawzy@fue.edu.eg
thanks alot

**Comment by bjergshen** [comment]
Have you download the dataset? can you give me a link?my mail is luojiejx@163.com
thanks a lot !@NerminSalem

**Comment by gina7152316** [comment]
Have you download the dataset? can you give me a link?
My mail: gina7152316@gmail.com
thanks a lot ! @NerminSalem
