### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by xzq-forever** [pathak22/context-encoder#21]
At B. Feature Learning part in Supplementary Material, you said," Unfortunately, we couldn’t train adversary with Alexnet Encoder." I wonder whether it is because you use Random region method?

**Comment by pathak22** [comment]
No, it was because I could not find right hyper-parameters in order for the training to not collapse. But note that the paper is from CVPR'16 at this point, so there might be better hyper-parameter settings now (1.5 yrs later).
