### ISSUE TITLE
Dataset for paris and imagenet

### ISSUE THREAD

**Issue by harshithabk** [pathak22/context-encoder#29]
@pathak22  Could you please share me the dataset that you used to train your models? 
My email id is harshi.384@gmail.com 
 
Also, when I tried to train the model [train.lua] with a different dataset, I obtained the following error:  
/home/ananya/torch/install/bin/luajit: /home/ananya/torch/install/share/lua/5.1/trepl/init.lua:389: module 'display' not found:No LuaRocks module found for display
	no field package.preload['display']
	no file '/home/ananya/.luarocks/share/lua/5.1/display.lua'
	no file '/home/ananya/.luarocks/share/lua/5.1/display/init.lua'
	no file '/home/ananya/torch/install/share/lua/5.1/display.lua'
	no file '/home/ananya/torch/install/share/lua/5.1/display/init.lua'
	no file './display.lua'
	no file '/home/ananya/torch/install/share/luajit-2.1.0-beta1/display.lua'
	no file '/usr/local/share/lua/5.1/display.lua'
	no file '/usr/local/share/lua/5.1/display/init.lua'
	no file '/home/ananya/.luarocks/lib/lua/5.1/display.so'
	no file '/home/ananya/torch/install/lib/lua/5.1/display.so'
	no file '/home/ananya/torch/install/lib/display.so'
	no file './display.so'
	no file '/usr/local/lib/lua/5.1/display.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/ananya/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:260: in main chunk
	[C]: in function 'dofile'
	...anya/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50  
Could you please help me resolve this issue?

**Comment by pathak22** [comment]
@harshithabk 
Email me and I will share a private link with you. I can't post the public link to this dataset due to the policy restrictions from Google Street View.
