### ISSUE TITLE
Organization of the train and val dataset 

### ISSUE THREAD

**Issue by yhlleo** [pathak22/context-encoder#3]
When I want to train my own model with my dataset, there is no explanation about the organization method of the data. I just put images into the folder `dataset/train` and `dataset/val`, but received a error:

```
/home/**/torch/install/bin/luajit: /home/**/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 4 callback] /home/**/context-encoder/data/dataset.lua:202: Could not find any image file in the given input paths
stack traceback:
	[C]: in function 'assert'
``` 

@pathak22

**Comment by pathak22** [comment]
Hi @yhlleo  ! 

Please look at the documentation provided here: https://github.com/pathak22/context-encoder#2-train-context-encoders

See point # 2, you need to create a folder named 'images' inside dataset/train/images/* and dataset/val/images/* ... and put all your image files inside it.

**Comment by yhlleo** [comment]
Thank you. It works well.
