### ISSUE TITLE
Segmentation results: What units are used?

### ISSUE THREAD

**Issue by Faur** [pathak22/context-encoder#31]
In Table 2 of the paper some segmentation performances are given, but I am not sure of the units. Is it accuracy, since there is a percentage sign? Or is it mean IoU, which is more standard (I don't recall seeing it with a percentage sign before though)

![image](https://user-images.githubusercontent.com/8115763/34908174-12c4f1fa-f88c-11e7-98d0-6a3288e96cec.png)

**Comment by pathak22** [comment]
This is indeed meanIoU -- which can range from 0 to 100. I agree percentage sign is not standard, but it is not wrong since it says how much of max meanIoU (which is 100) did the method gets which is equal to the actual meanIoU. 

Hope it clarifies! :-)
