### ISSUE TITLE
error whille testing my dataset

### ISSUE THREAD

**Issue by NerminSalem** [pathak22/context-encoder#34]
hii 
i tried training using the parisview dataset but i always get that error while testing after it finishes the training phase, which i can't figure out why ??
can u help ? @pathak22 
![screenshot from 2018-01-24 17-25-41](https://user-images.githubusercontent.com/26221951/35340385-a6784ba2-012b-11e8-8cd0-b3f3be9663c4.png)

**Comment by pathak22** [comment]
Is it at the end of training? You can also just comment out testing part and then later test it using demo.lua or test.lua?

**Comment by NerminSalem** [comment]
Thanks alot for yr reply but this error was due to that i used dataset of rectangular images when i resized them to a square iamges it worked.thanks
