### ISSUE TITLE
Regarding re-training a model

### ISSUE THREAD

**Issue by harshithabk** [pathak22/context-encoder#35]
@pathak22 
I understood the method to train with the existing dataset for `centre region inpainting model` with the below command as mentioned in README.md

DATA_ROOT=dataset/train display_id=11 name=inpaintCenter overlapPred=4 wtl2=0.999 nBottleneck=4000 niter=500 loadSize=350 fineSize=128 gpu=1 th train.lua  

This will give me the trained model "inpaintCenter_500_net_G.t7"
However I have two queries:
1) Suppose I want to re-train the already trained model "inpaintCenter_500_net_G.t7" with new dataset how do I achieve that?  
By referring the below link,
https://stats.stackexchange.com/questions/325803/retraining-cnn-model  
I understood that I need to load the weights from the old model to the new one. 
But how do we load the weights in this context-encoder code?
Kindly let me know the approach.  

2) Suppose I have trained a model "inpaintCenter_500_net_G.t7" with centre patch location, and I want to retrain the same model with different patch location, how do i achieve this?
Since I am a beginner to machine learning, kindly suggest.

**Comment by maryam089** [comment]
Regarding your first question, now a days i am also stuck on that ..... I also want to re-train the network with different set of images other than ImageNet dataset. So i tried to load parameters as well but its giving me error although i also tried to clone parameters from model to the network but no luck so far :( see the following link 
https://github.com/pathak22/context-encoder/issues/26
if you find any solution kindly help me too.

**Comment by harshithabk** [comment]
Okay, Thank you for the sharing the details.
In case I find any solution, will definitely post here.
Any idea about the 2nd question?

**Comment by maryam089** [comment]
did you read this 
https://github.com/pathak22/context-encoder/issues/5

if you change the patch location in the training code and train it afterwards then i think it will be fine but training on 100k imagenet dataset will take 6 days on 1 GPU system

**Comment by pathak22** [comment]
@maryam089 @harshithabk 

First, I would recommend training from scratch if you have large number of images in your dataset.

Second, if you don't have that many images and want to finetune from a pre-trained model. I would suggest looking at this [file](https://github.com/pathak22/context-encoder/blob/master/demo.lua#L27) and see how the network is first loaded. After this, the loaded network is same as the one defined [here](https://github.com/pathak22/context-encoder/blob/master/train.lua#L82-L196), and hence you won't need to define it again. This is more of a torch usage question than related to context encoder and i would encourage you to refer the official tutorials. Thanks!

**Comment by pathak22** [comment]
#26 Continue this discussion on the other thread. Closing this one.
