### ISSUE TITLE
is overlapPred used?

### ISSUE THREAD

**Issue by micklexqg** [pathak22/context-encoder#39]
in paper, it mention that overlap is 7, but the parameter is set 0 (default) in code.
is it used?

**Comment by pathak22** [comment]
This parameter is passed in the commands. It could be zero or non-zero in different cases. Please refer to the detailed commands in readme: https://github.com/pathak22/context-encoder#2-train-context-encoders

**Comment by micklexqg** [comment]
@pathak22 ,sorry for that. I run with the pytorch version before. I want to make sure that if the wtl2 is the 
![image](https://user-images.githubusercontent.com/13776012/37194350-c24e36bc-23a8-11e8-896f-2590a2e4f028.png) in the paper equation 3? maybe it is a little stupid. but I just want to make sure. thank you.

**Comment by pathak22** [comment]
No worries! Great! :-)

**Comment by micklexqg** [comment]
@pathak22 , thanks for your understanding. Must the rec weight plus the adv weight equal 1? it is so in the paper set (0.999+0.001). or they can be any value?

**Comment by ljjcoder** [comment]
@pathak22 when I use your pretrain model to test with overlap=4（net=models/inpaintCenter/imagenet_inpaintCenter.t7 name=imagenet_result imDir=images/imagenet overlapPred=4 manualSeed=222 batchSize=21 gpu=1 th demo.lua
） t
![imagenet_result](https://user-images.githubusercontent.com/40750189/52514723-48630c00-2c4f-11e9-9332-c08ed03f2591.png)
he result like bellow：

but when I use overlap=4 the result is very bad（net=models/inpaintCenter/imagenet_inpaintCenter.t7 name=imagenet_result imDir=images/imagenet overlapPred=3 manualSeed=222 batchSize=21 gpu=1 th demo.lua）
：
![imagenet_result3](https://user-images.githubusercontent.com/40750189/52514742-67fa3480-2c4f-11e9-8f75-7f278c0184e2.png)
is the model only work well on overlap=4？

**Comment by ljjcoder** [comment]
@pathak22 sorry， the second case is overlap=3
