### ISSUE TITLE
How to split the netG into two networks?

### ISSUE THREAD

**Issue by lingjiantian** [pathak22/context-encoder#4]
I am reproducing your work in "Context Encoders: Feature Learning by Inpainting" and I have trained the networks successfully. However, now I face a problem. I noticed that the netG extracts the features of a picture and then uses the features to fix the missing region of the picture. I am very interested in the features(i.e.,the 4000-unit bottleneck) and I hope to split the netG into two networks, an encode net and a decode net, so that I can use the encode one to transpose a picture into a vector or use the decode one to transpose a vector into a picture. I have no idea how to do it.
    I once tried to use ":add" to put an encode net and a decode net together into a netG but after training I found they are both nil while the netG worked well.

**Comment by pathak22** [comment]
The question you are asking is about torch. So you can play with following things: 
$ print(netG) -- to see index of modules.
$ netG.modules[2].output  -- it gives the output of 2nd module
$ netG.modules[1].modules[12].output  -- it gives the output of 12th module inside the 1st module (nested)

Please refer to Torch documentation for more details.
