### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by FindTheAnswer** [pathak22/context-encoder#47]
Could you give me the link of Paris Street-View Dataset?
My e-mail is 972346454@qq.com

**Comment by CVlin** [comment]
Could you give me the link of Paris Street-View Dataset?
My e-mail is 1908557731@qq.com

**Comment by leishuangshuang** [comment]
Did the author send you the dataset? If so, can you send it to me?
My e-mail is : 1046044085@qq.com

**Comment by gina7152316** [comment]
Did the author send you the dataset? If so, can you send it to me?
My e-mail is : gina7152316@gmail.com

**Comment by FindTheAnswer** [comment]
你好，不能私发。你给作者发邮件，他会给你链接。



---Original---

**Comment by pathak22** [comment]
Hi Everyone, 

Really sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak

**Comment by gina7152316** [comment]
﻿Hey, thanks for offering dataset, my email is: gina7152316@gmail.com.
I’m Sorry to get back to you so late.
