### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by DongPear** [pathak22/context-encoder#48]
Hi Pathak,
I'm a student studying on inpainting now. And I'd like to know if I can get dataset by email for private use.
And my email is lauren1997@qq.com.

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
