### ISSUE TITLE
Paris Street-View Dataset

### ISSUE THREAD

**Issue by zhangchencai** [pathak22/context-encoder#49]
Hi Pathak,
I am currently working on image inpainting algorothim and trying to train several model architectures. Can you share the Paris Street-View Dataset through a private link in my email address. That would be really great. Thanks.
Email: yyong_ma@outlook.com

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
