### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Mengyao-Li** [pathak22/context-encoder#52]
Hi,I'm studying on inpainting now.Could you share the Paris Street-View Dataset through a private link in my email address. Thanks.My email is 1592884408@qq.com

**Comment by leishuangshuang** [comment]
Did the author send you the dataset?

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
