### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lzzlxxlsz** [pathak22/context-encoder#54]
Hi,I'm studying on inpainting now.Could you share the Paris Street-View Dataset through a private link in my email address. Thanks.My email is 18731186906@163.com

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
