### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 12ycli** [pathak22/context-encoder#55]
Hi,I'm studying on inpainting now.Could you share the Paris Street-View Dataset through a private link in my email address. Thanks.My email is ucos-iii@qq.com

**Comment by zhangbaijin** [comment]
if you have seconds,could you share the Pairs Street-View Datset link to me address? 512631874@qq.com

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
