### ISSUE TITLE
Paris StreetView dataset

### ISSUE THREAD

**Issue by mxkai** [pathak22/context-encoder#57]
Hi，I'm trying some  algorithms of image restoration. Can you provide a data set of Paris StreetView dataset?Thanks.
Email:1502930420@qq.com

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
