### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by chen15956** [pathak22/context-encoder#58]
Hi Pathak,
I'm a student studying on inpainting now. And I'd like to know if I can get dataset by email for private use.

that is my e-mail : a0970739953@gmail.com

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
