### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 213GUI** [pathak22/context-encoder#59]
Hi, could you send me the private link of the street view datasets? My email address is pk2458807@gmail.com. Thank you very much!

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
