### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by renhaha123** [pathak22/context-encoder#60]
Hi, could you send me the private link of the street view datasets? My email address is renhaha123@foxmail.com. Thank you very much!

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
