### ISSUE TITLE
Request dataset help

### ISSUE THREAD

**Issue by jxw950605** [pathak22/context-encoder#61]
Hi
Our group is mainly studying the forensics of images and has been working on the forensics of image restoration recently. Could you please share the repaired images and masks you made to me? Thank you very much!
my email is XwangJu@163.com
Xingwang Ju
Nanjing University of information science and technology, China

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
