### ISSUE TITLE
Request dataset

### ISSUE THREAD

**Issue by Mengmengbai** [pathak22/context-encoder#63]
Good job.
Could you share me the dataset？
383736929@qq.com

**Comment by pathak22** [comment]
Hi, 

Sorry for the late reply here. As I mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
