### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by agyptl** [pathak22/context-encoder#64]
Could you please send me the dataset?My e-mail is ssttfit@outlook.com
Thank you so much.That's really helpful.

**Comment by LeeAndLee1** [comment]
Hi, Pathak, I want to train it by myself, but I don't know how to download the dataset.can you give me a link?Thank you.
My E-mail:1599417945@qq.com

**Comment by mxkai** [comment]
Could you please share the dataset with me?My e-mail is 154446011@qq.com,Thank you

**Comment by LeeAndLee1** [comment]
sorry!I have not heard from the author.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mxkai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 中午11:41
收件人:&nbsp;"pathak22/context-encoder"<context-encoder@noreply.github.com&gt;;
抄送:&nbsp;"Mr Snow"<1599417945@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [pathak22/context-encoder] dataset request (#64)




Could you please share the dataset with me?My e-mail is 154446011@qq.com,Thank you

**Comment by pathak22** [comment]
Hi Everyone, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
