### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by jose13579** [pathak22/context-encoder#65]
Hi, could you send me the private link of the Paris street view datasets? My email address is jluisflores357@gmail.com. Thank you very much!

**Comment by cwliang1219** [comment]
I am currently working on image inpainting. Can you share the dataset through a private link in my email address. Thanks.
Email: d9307206@gmail.com

**Comment by aamirk5** [comment]
I am currently working on image inpainting. Could you please send the image inpainting dataset private link to my email address. Thanks.
Email: aamir.uettaxila@gmail.com

**Comment by pathak22** [comment]
Hi Everyone, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
