### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by DingzhouWang** [pathak22/context-encoder#67]
Hi, I am currently studying on inpainting. Could you please share The Paris Street-View Dataset through a private link in my email address. My email is 1614081533@qq.com. Thanks!

**Comment by ShamelessBei** [comment]
I am in china. You want chinese city's data?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DingzhouWang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 中午11:44
收件人:&nbsp;"pathak22/context-encoder"<context-encoder@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[pathak22/context-encoder] dataset (#67)





 
Hi, I am currently studying on inpainting. Could you please share The Paris Street-View Dataset through a private link in my email address. My email is 1614081533@qq.com. Thanks!

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
