### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by aamirk5** [pathak22/context-encoder#68]
Dear Sir,
Could you please email me dataset for learning image inpainting link.. my email id is as follow:
aamir.uettaxila@gmail.com
Thanks and best regards:

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
