### ISSUE TITLE
Paris StreetView dataset

### ISSUE THREAD

**Issue by zhengbowei** [pathak22/context-encoder#69]
Hi，I'm trying some algorithms of image inpainting. Can you provide a data set of Paris StreetView dataset?Thanks.
Email:734249947@qq.com

**Comment by jiashide** [comment]
Hi Pathak,
I am working on image inpainting and need these images as training datasets badly. Could you please share a link with me? Thanks a lot!
Email:1354772109@qq.com

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
