### ISSUE TITLE
don't need validation data

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [pathak22/context-encoder#7]
@pathak22 
In the readme file, you wrote how to make the dataset folder
"mkdir -p /path_to_wherever_you_want/mydataset/train/images/
# put all training images inside mydataset/train/images/
mkdir -p /path_to_wherever_you_want/mydataset/val/images/
# put all val images inside mydataset/val/images/"

However, i only set the train folder and not set the val folder, the train process go on wheels . Was the validation data needless?

**Comment by pathak22** [comment]
It is not needed to train the model. It is required only if you want to do inpainting using the trained model on val set (see step-4).
