### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by SallyHuangImperial** [pathak22/context-encoder#70]
Dear Sir,
Could you please email me the dataset for the learning image inpainting link.
My email address is huangsally5686@gmail.com
Thanks!

best wishes
Sally

**Comment by Lillian1082** [comment]
Dear Sir,
Could you please email me the dataset for the learning image inpainting link.
My email address is yang.liu3@anu.edu.au
Thanks!

best wishes
Yang

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
