### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by yabg-shuai666** [pathak22/context-encoder#71]
Dear Sir,
Could you please email me the paris dataset for the learning image inpainting link.
My email address is 326605441@qq.com
Thanks!

best wishes

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak

**Comment by yabg-shuai666** [comment]
Hi，I'm trying some algorithms of image restoration. Can you provide a data set of Paris StreetView dataset?Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pathak22/context-encoder"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 凌晨5:27
收件人:&nbsp;"pathak22/context-encoder"<context-encoder@noreply.github.com&gt;;
抄送:&nbsp;"杨帅"<326605441@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pathak22/context-encoder] Dataset (#71)





 
Hi,
 
As mentioned here, please send me an email to get access to the dataset. I will reply with a shared link. Thanks!
 
Best,
 Deepak
