### ISSUE TITLE
Paris StreetView

### ISSUE THREAD

**Issue by jiashide** [pathak22/context-encoder#72]
Hi Pathak,
I am working on image inpainting and need these images as training datasets badly. Could you please share a link with me? Thanks a lot!
Email:1354772109@qq.com

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
