### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Algolzw** [pathak22/context-encoder#73]
Hi Pathak,
I am working on image inpainting and need these images as training datasets badly. Could you please share a link with me? Thanks a lot!
Email:algo_lzw@yahoo.com

**Comment by gina7152316** [comment]
Hi Pathak,
I am working on image inpainting and need these images as training datasets badly. Could you please share a link with me? Thanks a lot!
Email: gina7152316@gmail.com/ gina7152316@yahoo.com.tw

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
