### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by inspectred** [pathak22/context-encoder#76]
Hi Pathak,
Could you please share this inpainting dataset with me as I'm doing my Msc. theses on image inpainting? Thanks a lot!
Email: danydanydood@gmail.com

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
