### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by weizitai** [pathak22/context-encoder#78]
Hi Pathak,
      I am doing research related to image restoration, but there is no such Paris StreetView Dataset, please share your data set with me, thank you a lot.
Email:w406141176@gmail.com

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
