### ISSUE TITLE
Must  the inpainting region be quare?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [pathak22/context-encoder#8]
Setting the inpainting region rectangle  result to error. 
Must  the inpainting region be quare?

**Comment by pathak22** [comment]
@xuyifeng-nwpu 
No it need not be square. But for non-square arbitrary regions, you can train your own models using this file: https://github.com/pathak22/context-encoder/blob/master/train_random.lua

Instructions are given in readme.
