### ISSUE TITLE
Dataset Request.

### ISSUE THREAD

**Issue by funkdub** [pathak22/context-encoder#80]
Hi Pathak,

I am doing research related to image inpainting, but there is no such Paris StreetView Dataset, please share your dataset with me, thank you a lot. My e-mail: fengx@bjfu.edu.cn

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset. I will reply with a shared link. Thanks!

Best,
Deepak
