### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by baahuabhi** [pathak22/context-encoder#81]
Hi Pathak,
               I need Paris view dataset for my image inpainting B-tech project , please send me as soon as possible.
              "abhiramchowdary.m99@gmail.com"

**Comment by pathak22** [comment]
Hi, 

As mentioned [here](https://github.com/pathak22/context-encoder#6-paris-street-view-dataset), please send me an [email](https://www.cs.cmu.edu/~dpathak/) to get access to the dataset.

Thanks!
Deepak
