### ISSUE TITLE
where is the Channel-wise fully-connected layer ?

### ISSUE THREAD

**Issue by BoyuanJiang** [pathak22/context-encoder#9]
Is there a Channel-wise fully-connected layer in the Torch version codes?I don't find where it is.

**Comment by BoyuanJiang** [comment]
sorry i have known it

**Comment by sunshineatnoon** [comment]
@BoyuanJiang Hi, could you kindly point the fully-connected layer to me? I can't find it either.

**Comment by royal-feng** [comment]
@BoyuanJiang  I want to ask you for whether the Channel-wise fully-connected layer is the nBottleneck in the code? My understanding that is the transition layer between the encoder and decoder, is it right?
